### ISSUE TITLE
Inter-process communication support

### ISSUE THREAD

**Issue by czapek1337** [Andy-Python-Programmer/aero#18]
Currently Aero is lacking any sort of IPC layer, whether it be UNIX domain sockets or a custom IPC solution. Together with @Andy-Python-Programmer we came to a conclusion that for the sake of compatibility with other software (ease of porting to Aero) we will implement UNIX domain socket support for Aero, as well as other IPC primitives like signals. This is a tracking issue for progress of IPC in Aero. The list is going to be updated with more details as we go to provide a better view of the task.

- [x] Implement socket support in the kernel
- [x] Implement support for UNIX domain sockets (simplest form of IPC)
- [x] Write a basic "echo" server to demonstrate the IPC capabilities :^)

**Comment by Andy-Python-Programmer** [comment]
- [ ] sys_socket
- [ ] sys_connect
- [ ] sys_bind
- [ ] sys_listen
- [ ] sys_accept
