### ISSUE TITLE
Please add some prerequisite packages to README.md

### ISSUE THREAD

**Issue by omac777** [Andy-Python-Programmer/aero#26]
sudo apt-get install cdrskin xorriso xfburn udftools dvd+rw-tools growisofs

These aren't all necessary but handy just in case.
xorriso definitely is necessary.

**Comment by Andy-Python-Programmer** [comment]
Resolved in https://github.com/Andy-Python-Programmer/aero/commit/f5588875b4a061cce7d6beedd38cc0d11e02ff84.
