### ISSUE TITLE
Add Gitpod integration

### ISSUE THREAD

**Issue by jwpjrdev** [Andy-Python-Programmer/aero#33]
Gitpod (https://gitpod.io) is a cool and dandy solution to “works on my machine” issues!
Workspaces are ephemeral and run in the cloud. It also allows you to work from any device. I personally use an iPad.

A `.gitpod.yml` file would be the only addition. This file can handle things such as a VNC client (as a remote desktop), dependency installation, etc.

I'll probably create a PR for this sometime soon.

**Comment by Andy-Python-Programmer** [comment]
> I'll probably create a PR for this sometime soon.

That would be awesome!
