### ISSUE TITLE
Rewrite areo.py in rust

### ISSUE THREAD

**Issue by leapofazzam123** [Andy-Python-Programmer/aero#36]
Make it a cargo build.rs

**Comment by czapek1337** [comment]
mfw I rewrote it from rust to python to make it faster, then someone comments "rewrite it in rust" :trollface:

**Comment by Andy-Python-Programmer** [comment]
Now rewrite it again :trollface:. Oh fun, github has an actual troll face emote.

**Comment by YusufKhan-gamedev** [comment]
Rewrite it in POSIX shell

**Comment by Andy-Python-Programmer** [comment]
no

**Comment by czapek1337** [comment]
> Rewrite it in POSIX shell

I haven't gone insane *just yet*

**Comment by YusufKhan-gamedev** [comment]
> > Rewrite it in POSIX shell
> 
> I haven't gone insane _just yet_

That was a real suggestion, create a separate rewrite in POSIX shell for when its better(when not using bash)

**Comment by Froggo8311** [comment]
Lol put zsh on there

**Comment by Froggo8311** [comment]
I thought rust was faster than python? If it is, why was it originally rewritten into python?

**Comment by Andy-Python-Programmer** [comment]
Of course it is, we rewrote it because of the compile time of the builder.

**Comment by jwpjrdev** [comment]
shouldn't this issue be closed?

**Comment by Andy-Python-Programmer** [comment]
Yes. Thanks!
