### ISSUE TITLE
Adding C drivers into aero

### ISSUE THREAD

**Issue by YusufKhan-gamedev** [Andy-Python-Programmer/aero#39]
There are certain (very) large drivers that would be infeasible to port to rust(ie. drm). How would I interact with the kernel interfaces, ioctl stuff, and how does pcie kernel interface work?

**Comment by Andy-Python-Programmer** [comment]
if you want you can do it by `extern`ing the kernel functions in c but eh we will do it in rust dw :^)

**Comment by YusufKhan-gamedev** [comment]
> if you want you can do it by `extern`ing the kernel functions in c but eh we will do it in rust dw :^)
Your going to port all of that to rust? Your going to spend money to test the cards, add GEM?

Anyway, how would I add ioctl stuff?
