### ISSUE TITLE
Questions and suggestions

### ISSUE THREAD

**Issue by JakubGawron23** [Andy-Python-Programmer/aero#4]
I am very impressed with your project and have a few questions about the project. 😊 
1. The first question is:
Is the limine bootloader only used as a bootloader for BIOS or also UEFI ( although if limine was used for UEFI it would make no sense to use **aero_boot**)?
2. Is it possible to create **pixel based framebuffer** ?
3. What encouraged you to create this project ?
That's all for now. 😊 I look forward to your reply.

**Comment by Andy-Python-Programmer** [comment]
Hi @JakubGawron23! Thanks 🤩! We currently use the limine bootloader for chain loading purposes, the documentation for limine chain loading is not documented yet and is in my roadmap. As from the README:

> Chainloading is a technique that allows one bootloader to call another bootloader as if the system had just booted up. Aero's bootloader has support for chainloading. Check out the Aero Chainloading docs to get more information about how to use this feature.

The chain loading docs for grub can be found at `./docs/chainloading.md`: <https://github.com/Andy-Python-Programmer/aero/blob/master/docs/chainloading.md>

We currently actually use a pixel based, RGB based framebuffer. 

https://github.com/Andy-Python-Programmer/aero/blob/2ce3ab0d651dd4463700462d526cba047acbea76/src/aero_gfx/src/debug/rendy.rs#L27

https://github.com/Andy-Python-Programmer/aero/blob/2ce3ab0d651dd4463700462d526cba047acbea76/src/aero_boot/src/main.rs#L65

My encouragement was to build a more secure, modular, and performing operating system and kernel using the features the modern and widely used rust programming language. The aero kernel is inspired from inspired by the Linux Kernel and the Zircon Kernel.

I will keep this issue open for the limine chain loading docs.

**Comment by Andy-Python-Programmer** [comment]
## Updates

> Is the limine bootloader only used as a bootloader for BIOS or also UEFI ( although if limine was used for UEFI it would make no sense to use aero_boot)?

Aero has completely now switched to limine which would also allow the user to pick any bootloader that the user wants (just like linux) and the bootloader should be able to boot the kernel using the stivale2 protocol easily. The aero's custom bootloader had a lot lot of problems and I did not feel like it was the effort to fix them all as it was kindof being a project by itself. So I have decided to create my own stivale2 bootloader in rust so everyone can use it too. And the biggest advantage of this is that now we already have support for BIOS and UEFI and also aarch64 boot, also limine provides a sweet boot menu.
