### ISSUE TITLE
creating kernel "modules"

### ISSUE THREAD

**Issue by YusufKhan-gamedev** [Andy-Python-Programmer/aero#41]
How would I access the kernel interfaces with kernel privileges (i.e. make a kernel module) in aero?

**Comment by Andy-Python-Programmer** [comment]
For a simple hello world kernel module example which is directly linked into a modules section in the kernel itself:

1. Create a new in `src/aero_kernel/src/drivers/`, we will call it `hello.rs`
2. Register the init module function. 
```rs
fn hello_init() {
    log::debug!("Hello, World from Aero kernel module!");
}

// register the module init function :^)
aero_kernel::module_init!(hello_init);
```
3. Profit

**Comment by YusufKhan-gamedev** [comment]
> For a simple hello world kernel module example which is directly linked into a modules section in the kernel itself:
> 
>     1. Create a new in `src/aero_kernel/src/drivers/`, we will call it `hello.rs`
> 
>     2. Register the init module function.
> 
> 
> ```rust
> fn hello_init() {
>     log::debug!("Hello, World from Aero kernel module!");
> }
> 
> // register the module init function :^)
> aero_kernel::module_init!(hello_init);
> ```
> 
>     3. Profit

How would I load the kernel module on runtime?

**Comment by Andy-Python-Programmer** [comment]
> How would I load the kernel module on runtime?

Currently we don't support loading kernel modules at runtime yet. Though soon I could implement support for it.
