### ISSUE TITLE
Add documentation on PCI KPI

### ISSUE THREAD

**Issue by YusufKhan-gamedev** [Andy-Python-Programmer/aero#45]
The PCI kernel interfaces for aero have to be properly documented, your code doesnt explain itself.

**Comment by Andy-Python-Programmer** [comment]
What specifically are you confused about.

**Comment by YusufKhan-gamedev** [comment]
> What specifically are you confused about.

Every single function, how do I r/w to a specif device+vendor, how do I find the base address in memory for a pci device with knowing the device+vendor. There is currently minimal documentation on pci.rs.

**Comment by StaticSaga** [comment]
https://wiki.osdev.org/PCI
I don't know much Rust well, but the code is very readable if you have osdev and PCI knowledge already.

**Comment by YusufKhan-gamedev** [comment]
> https://wiki.osdev.org/PCI I don't know much Rust well, but the code is very readable if you have osdev and PCI knowledge already.

I thought that, until I actually tried to do something with it....

**Comment by YusufKhan-improves-shit** [comment]
![image](https://user-images.githubusercontent.com/98565009/151683648-a6d71e2e-94a1-4efd-88e1-9b70d8ec746e.png)
On gh pages this doesn't show read() write() etc.

**Comment by czapek1337** [comment]
> On gh pages this doesn't show read() write() etc.

because there isn't such functions, do you even know how PCI works? lol

**Comment by YusufKhan-gamedev** [comment]
> because there isn't such functions, do you even know how PCI works? lol

I know that, its under PCIHeader, but still 
![image](https://user-images.githubusercontent.com/54283715/151721476-ad8ad628-3614-4bf3-9b29-63844aa23aa4.png)
is *a bit* buried and doesnt include how someone could actually use those functions(mostly) just that you have to provide a PciHeader and a offset.

**Comment by Andy-Python-Programmer** [comment]
> is a bit buried

Since you call the function on a PCI header lol. This is like basic and you should know this when programming :^) This function is **ment** to be called on a PCI header.

> People who dont understand how the hardware interfaces with other hardware shouldnt be barred from doing kernel work. kernel interfaces should always be documented, put a comment.

They are, you should just dig deeper into the documentation. You cannot expect the whole docs of every single struct to be on a single page. That would be messy right? Thats why they are dont in sub pages. Its done for a reason mate :^)

> how someone could actually use those functions(mostly) just that you have to provide a PciHeader and a offset.

Exactly you call this function on a PCI header and provide it an offset thats it :^) nothing special. Its easy. What is confusing about it?

**Comment by YusufKhan-gamedev** [comment]
How do I rw bytes from a specific vendorxdevice id

**Comment by YusufKhan-gamedev** [comment]
that seems like something to put in a pr.....
