### ISSUE TITLE
driver::lai: failed at an assert

### ISSUE THREAD

**Issue by coolgatplayz** [Andy-Python-Programmer/aero#74]
![image](https://user-images.githubusercontent.com/81543231/175182953-1766ba18-a1cf-470d-8379-d6d4af9d8a49.png)

Running inside `Oracle VM VirtualBox`
Version: Latest prebuilt

**Comment by uityyy** [comment]
I see the same on the latest nightly in VirtualBox many months later. Does anyone know the latest nightly that is actually bootable?

**Comment by uityyy** [comment]
Does VirtualBox crash this way for everyone, or is it based on the host CPU? My daily driver has a 2011 Sandy Bridge CPU that was high-end for its time and thus feels fast and snappy despite being twelve years old, so my host cpu flags are

`fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts md_clear flush_l1d`

**Comment by Andy-Python-Programmer** [comment]
https://github.com/Andy-Python-Programmer/aero/commit/165c84acc560730bd10b30b0d63b75632102a92a
